In [3]:
import pandas as pd
import numpy as np
from sklearn.ensemble import RandomForestClassifier
from sklearn.cross_validation import train_test_split
from sklearn.model_selection import KFold
from sklearn import cross_validation
import timeit
from sklearn import svm
from sklearn.model_selection import cross_val_score

C:\Users\xd21\AppData\Local\Continuum\Anaconda3\lib\site-packages\sklearn\cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)


In [2]:
df = pd.read_csv('data0.csv', low_memory=False)

In [3]:
class_original = df['class']
del df['class']

In [4]:
df_x = df.drop('newclass', axis = 1).astype(np.float)
df_y =  df['newclass'].astype('category')
s_x = df_x[0:10000]
s_y = df_y[0:10000]

t_x = df_x[10000:10030]
t_y = df_y[10000:10030]

In [ ]:
# 5 folds cross validation on Random Forest, using original categories

start = timeit.default_timer()
num_folds = 5
num_instances = len(df)
seed = 7
num_trees = 500
max_features = 'auto'
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features,
min_samples_leaf=50)

results= cross_val_score(model, df_x,  
                        class_original.astype('category'), cv=kfold, n_jobs=-1)


stop = timeit.default_timer()

print(stop - start) 

print(results)

In [29]:
# 5 folds cross validation on Random Forest

start = timeit.default_timer()
num_folds = 5
num_instances = len(df)
seed = 7
num_trees = 500
max_features = 'auto'
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features,
min_samples_leaf=50)

results= cross_val_score(model, df.drop('newclass', axis = 1).astype(np.float),  
                         df['newclass'].astype('category'), cv=kfold, n_jobs=-1)


stop = timeit.default_timer()

print(stop - start) 

print(results)

576.7984897810531
[ 0.5059921   0.50845792  0.51281211  0.51338116  0.51098427]


In [27]:
# 10 folds cross validation on 4-NN

from sklearn.neighbors import KNeighborsClassifier



start = timeit.default_timer()
num_folds = 10
num_instances = len(df)
seed = 7

for i in range(3,11):
    kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
    knn_model = KNeighborsClassifier(n_neighbors = i, n_jobs=-1)

    results_knn = cross_val_score(knn_model, df_x,  
                             df_y, cv=kfold, n_jobs=-1)
    print(results_knn)


stop = timeit.default_timer()

print(stop - start) 

# print(results_knn)

[ 0.45784047  0.45308135  0.45882191  0.45851152  0.45544213  0.45482135
  0.45720099  0.45282108  0.45423507  0.45940819]
[ 0.46594475  0.45859917  0.46644365  0.46461581  0.46151193  0.46458132
  0.46689199  0.46323631  0.46396055  0.46468478]
[ 0.46559989  0.45984067  0.46509863  0.46792661  0.46292592  0.46482273
  0.46551248  0.46285695  0.46599531  0.46782315]
[ 0.46815188  0.46570335  0.47082356  0.4696165   0.46592633  0.46785764
  0.47144434  0.47027176  0.46927162  0.47341013]
[ 0.47304894  0.46739318  0.47506553  0.4762381   0.46634018  0.47137536
  0.47306525  0.47316871  0.4729273   0.47303076]
[ 0.47504914  0.47246267  0.47661746  0.47492758  0.46982342  0.47178921
  0.47565181  0.47599669  0.4729273   0.47589323]
[ 0.47898058  0.47463531  0.47510001  0.47823838  0.47189267  0.47368603
  0.47716926  0.47782453  0.47334115  0.47720375]
[ 0.47984274  0.47446288  0.47668644  0.47599669  0.47572079  0.47675541
  0.4814802   0.47934198  0.47768658  0.48003173]
666.034668881959

In [ ]:
# 10 folds cross validation on boosting

from sklearn.ensemble import GradientBoostingClassifier



start = timeit.default_timer()
num_folds = 10
num_instances = len(df)
seed = 7


kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)

boost_model = GradientBoostingClassifier()

results_boost = cross_val_score(boost_model, df_x, df_y, cv=kfold, n_jobs=-1)
print(results_boost)


stop = timeit.default_timer()

print(stop - start) 

print(results_boost)

In [ ]:
# 10 folds cross validation on Ridge Regression

from sklearn.linear_model import LogisticRegression


start = timeit.default_timer()
num_folds = 5
num_instances = len(df)
seed = 7


kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)

for i in [1000]:
    lasso_model = LogisticRegression(penalty = 'l1', n_jobs = -1, solver = 'liblinear', C = i)

    results_lasso = cross_val_score(lasso_model, df_x, df_y, cv=kfold, n_jobs=-1)
    print(results_lasso)


stop = timeit.default_timer()

print(stop - start) 



In [3]:
################## New Data
df1 = pd.read_csv('new.csv', low_memory=False)

df1_x = df1.drop('newclass', axis = 1).astype(np.float)
df1_y =  df1['newclass'].astype('category')


In [4]:
# 5 folds cross validation on Random Forest

start = timeit.default_timer()
num_folds = 5
num_instances = len(df1)
seed = 7
num_trees = 500
max_features = 'auto'
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features,
min_samples_leaf=50)

results1= cross_val_score(model, df1_x, df1_y, cv=kfold, n_jobs=-1)


stop = timeit.default_timer()

print(stop - start) 

print(results1)

880.7879981256418
[ 0.50499198  0.50823375  0.51143261  0.51270865  0.50924265]


In [6]:
results1

array([ 0.50499198,  0.50823375,  0.51143261,  0.51270865,  0.50924265])

In [11]:
from sklearn.neighbors import KNeighborsClassifier



start = timeit.default_timer()
num_folds = 10
num_instances = len(df1)
seed = 7

for i in range(3,11):
    kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
    knn_model = KNeighborsClassifier(n_neighbors = i, n_jobs=-1)

    results1_knn = cross_val_score(knn_model, df1_x,  
                             df1_y, cv=kfold, n_jobs=-1)
    print(results1_knn)


stop = timeit.default_timer()

print(stop - start) 

# print(results_knn)

[ 0.45759906  0.45297789  0.45889088  0.45833908  0.45520072  0.45478687
  0.45751138  0.45306249  0.45430404  0.45920127]
[ 0.46611718  0.45859917  0.46647813  0.46454683  0.46120155  0.46440888
  0.46702994  0.46313285  0.46399503  0.46475376]
[ 0.46549643  0.45984067  0.46496068  0.46792661  0.46285695  0.46482273
  0.46571941  0.46285695  0.46613326  0.4679611 ]
[ 0.46801393  0.46559989  0.47103049  0.46958201  0.46582287  0.46765071
  0.4712719   0.47034074  0.46916816  0.47327218]
[ 0.4731524   0.46742766  0.47520348  0.47620361  0.4663057   0.47137536
  0.47313423  0.47327218  0.47285833  0.47309974]
[ 0.4751526   0.47249715  0.47661746  0.47482411  0.46985791  0.4718237
  0.47561733  0.47603118  0.47303076  0.47582425]
[ 0.47884264  0.47453185  0.47510001  0.47813492  0.47189267  0.47378949
  0.47720375  0.4778935   0.47341013  0.47716926]
[ 0.47973928  0.47460082  0.47682439  0.47606566  0.47585874  0.47689336
  0.48154918  0.47930749  0.4776176   0.4801007 ]
737.6812171833371

In [4]:
###   Use 30,000 DataSet, Original Categories
df = pd.read_csv('data_sample.csv', low_memory=False)

class_original = df['class']
del df['class']

df_x = df.drop('newclass', axis = 1).astype(np.float)
df_y =  df['newclass'].astype('category')


In [6]:

# 5 folds cross validation on Random Forest

start = timeit.default_timer()
num_folds = 5
num_instances = len(df)
seed = 7
num_trees = 500
max_features = 'auto'
kfold = cross_validation.KFold(n=num_instances, n_folds=num_folds, random_state=seed)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features,
min_samples_leaf=50)

results1= cross_val_score(model, df_x, df_y, cv=kfold, n_jobs=-1)


stop = timeit.default_timer()

print(stop - start) 

print(results1)

46.923436047106634
[ 0.22222222  0.46856287  0.21390552  0.25465735  0.33133733]


In [5]:
# read in original new data set and take test set
df1 = pd.read_csv('new.csv', low_memory=False)

df1_x = df1.drop('newclass', axis = 1).astype(np.float)
df1_y =  df1['newclass'].astype('category')



In [6]:
from numpy.random import randint
import random

random.seed(123)
idx = randint(0,len(df1_x), 100000)
test_x = df1_x.loc[idx]
test_y = df1_y[idx]

In [7]:
df_x = df.drop('newclass', axis = 1).astype(np.float)
df_y =  df['newclass'].astype('category')

# Random Forest


num_instances = len(df)
seed = 7
num_trees = 500
max_features = 'auto'

model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features,
min_samples_leaf=50)
model = model.fit(df_x, df_y)


In [8]:
pred1 = model.predict(test_x)
print(np.sum(np.sum(test_y == pred1)/len(test_x)))

0.49943


In [9]:
# 10-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 10, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)


In [10]:
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.47204


In [11]:
# 8-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 8, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)

In [12]:
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.47042


In [13]:
# 6-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 6, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)

In [14]:
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.468


In [15]:
# Boosting

from sklearn.ensemble import GradientBoostingClassifier


boost_model = GradientBoostingClassifier()

boost_model = boost_model.fit(df_x, df_y)


In [49]:
pred_boost = boost_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_boost)/len(test_x)))

0.50361


In [16]:
# Ridge Regression

from sklearn.linear_model import LogisticRegression

lasso_model = LogisticRegression(penalty = 'l1', n_jobs = -1, solver = 'liblinear', C = 147)

lasso_model = lasso_model.fit(df_x, df_y)

In [1]:
pred_las = lasso_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_las)/len(test_x)))

NameError: name 'lasso_model' is not defined

In [17]:
# Lasso Regression

from sklearn.linear_model import LogisticRegression

las_model = LogisticRegression(penalty = 'l2', n_jobs = -1, solver = 'sag', C = 147)

las_model = las_model.fit(df_x, df_y)

In [53]:
pred_lasso = las_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_lasso)/len(test_x)))

0.43274


In [26]:
# new test set
random.seed(24)
idx = randint(0,len(df1_x), 100000)
test_x = df1_x.loc[idx]
test_y = df1_y[idx]


In [27]:
# RF
pred1 = model.predict(test_x)
print(np.sum(np.sum(test_y == pred1)/len(test_x)))

0.50238


In [28]:
# 10-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 10, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.47327


In [29]:
# 8-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 8, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.47126


In [30]:
# 6-NN

from sklearn.neighbors import KNeighborsClassifier

knn_model = KNeighborsClassifier(n_neighbors = 6, n_jobs=-1)
knn_model = knn_model.fit(df_x, df_y)
pred_knn = knn_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_knn)/len(test_x)))

0.46937


In [31]:
# Boosting
pred_boost = boost_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_boost)/len(test_x)))

0.50493


In [32]:
# Ridge
pred_las = lasso_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_las)/len(test_x)))

0.49328


In [33]:
# Lasso
pred_lasso = las_model.predict(test_x)
print(np.sum(np.sum(test_y == pred_lasso)/len(test_x)))

0.43279
